### ISSUE TITLE
why require internally?

### ISSUE THREAD

**Issue by jescalan** [jstransformers/jstransformer-reshape#1]
https://github.com/jstransformers/jstransformer-reshape/blob/master/index.js#L16

What if the plugin is from a different source, or is passed as a function by the user? I'd much prefer the ability to require the plugin myself and pass it in for this reason, avoids any possible edge case.

**Comment by RobLoach** [comment]
Optimally, it would support both passing in the plugin objects, or the require strings.

**Comment by calebeby** [comment]
Good point, I'll implement it like we did for jstransformer-stylus

**Comment by calebeby** [comment]
@jescalan I added this behavior.

https://github.com/jstransformers/jstransformer-reshape/blob/master/test/plugin-direct/options.js

**Comment by jescalan** [comment]
@calebeby looks great! maybe add to the readme? I can PR this if you want

**Comment by calebeby** [comment]
Thanks, you can PR, or if not I'll get to it this weekend.
